require 'rubygems'
require 'rake'
require 'fileutils'

@source_path = File.expand_path(__dir__)

# generate ~/.emacs from template
dotemacs_target = File.join(ENV['HOME'], ".emacs")
dotemacs_template_source = File.join(@source_path, "dotemacs_template")

file dotemacs_target => dotemacs_template_source do
  puts "* generating #{dotemacs_target} ..."
  File.open(dotemacs_target,"w") do |outfile|
    outfile.puts ";; this file was automatically generated by rake from #{@source_path}. do not overwrite."
    File.open(dotemacs_template_source) do |infile|
      infile.each_line do |line|
        outfile.puts line.gsub('__DIR__', @source_path)
      end
    end
  end
end

desc "install ~/.emacs"
task :install => dotemacs_target

desc "remove ~/.emacs"
task :clean do
  FileUtils.rm_f dotemacs_target, :verbose => true
end

task :default => [:install]
